### ISSUE TITLE
dnd-character stub is actually the example solution

### ISSUE THREAD

**Issue by glennj** [exercism/pyret#168]
@BNAndras

**Comment by glennj** [comment]
Perhaps for this exercise, we provide less help in the stub? Maybe just

```pyret
use context essentials2020 # Don't delete this line when using Pyret on Exercism 

provide:
  data Character
end

data Character:
  ...
end
```

**Comment by BNAndras** [comment]
Yeah, it looks like I didn't revert the stub. Something more concise would be fine, but an instructions append is warranted then telling folks up front we're using a data declaration and linking to the official docs.
