### ISSUE TITLE
Implement Two Fer?

### ISSUE THREAD

**Issue by BNAndras** [exercism/pyret#24]
Pyret doesn't have default argument values. We could pass in an [Option](https://pyret.org/docs/latest/option.html), using the none variant to represent a name not being passed.

```
some("hello").or-else("you") # "hello"
none.or-else("you") # "you"

but not

some(none).or-else("you") # none
```

**Comment by iHiD** [comment]
Lots of other languages share this problem.

The actual examplar can be whatever you want - it never gets seen by anyone, it's just for CI purposes. 

The beauty will be in the variations that people come up with. Adding an Approach for both that and the more basic version (e.g. https://github.com/exercism/go/blob/main/exercises/practice/two-fer/.meta/example.go) would be nice! :)

**Comment by BNAndras** [comment]
Yeah, that's a great point. I didn't want to conflate an empty string with none, but Option does railroad the student towards a solution without a lot of room for mentoring. At the same time, it'd be good to expose them to Options at some point since several built-ins return those. That could be a syllabus concept when we get there.
