### ISSUE TITLE
Update track documentation for Windows / WSL

### ISSUE THREAD

**Issue by BNAndras** [exercism/pyret#41]
In my testing, it appears the Pyret compile server doesn't work on Windows (but does on Linux and MacOS). I've confirmed that using WSL on Windows works so we should update any documentation to reflect that workaround

**Comment by Chidinma1709** [comment]
The pyret doesnt't work on window

**Comment by BNAndras** [comment]
Unfortunately, troubleshooting Pyret on Windows is out of scope for this issue which is specifically regarding documentation of the command-line Pyret documentation. For support, I'd suggest using the official Pyret discussion mailing list at https://groups.google.com/g/pyret-discuss or filing an issue with https://github.com/brownplt/pyret-lang.
