### ISSUE TITLE
ETL output dict container type should match input dict container type

### ISSUE THREAD

**Issue by BNAndras** [exercism/pyret#74]
@meatball133, would it be a bother for you to switch the tests to expect that a string-dict is returned? You can use the freeze() method on mutable-string-dict so example.arr wouldn't need to change much. Since string-dicts and mutable-dicts work the same here for our purposes, I think we should keep the input and output types the same for simplicity.

**Comment by meatball133** [comment]
I can take a look at it tomorrow.

**Comment by BNAndras** [comment]
Much appreciated.
