### ISSUE TITLE
Proposal for pending tests

### ISSUE THREAD

**Issue by BNAndras** [exercism/pyret#93]
@ErikSchierboom, Pyret doesn't have a way to mark tests pending. My thought was I could use a multiline comment (block comment in Pyret) to hide a test from Pyret. The student needs to remove the surrounding #| and |# lines so Pyret can see and run a given test. These would be the only multiline comments in the test files so it's easy to account for in the test runner setup as well. The only problem is that since Pyret won't know there's a commented-out test, it can't alert the student to the presence of pending tests like some other tracks' testing frameworks might.

```
fun foo():
  true
end

check "this test will run every time":
  foo() is true
end

#|
   # This test is pending. Remove the surrounding #| and |# lines to run this test.
check "this test will only run after the surrounding block comment is removed":
  hi() is true
end
|#

check "this test will run whether or not the second test is commented out":
  foo() is-not true
end
```

**Comment by ErikSchierboom** [comment]
I don't think I've ever seen a track use that strategy, and I'm unsure whether this is something the student will understand. Maybe you could look at what some other tracks do? One option would be to have the skipped tests do an early return:

```
check "this test will run whether or not the second test is commented out":
  return # Remove this line to un-skip the test
  foo() is-not true
end
```

**Comment by BNAndras** [comment]
```check "always runs since testing operator is detected at run time":
  foo() is true
end

skip = true
check "only sees/runs test when skip is false":
  when skip == false:
    foo() is true
  end
end
```

If skip is true, Pyret won't hit the testing operator inside the when block so no test is run. If skip is false, the condition for the when block is satisfied and we run the test. This avoids a skipped test passing since there's no test until we're ready to run it for real.

**Comment by BNAndras** [comment]
```
fun foo():
  true
end

fun foo-is-true():
  check "foo is true":
    foo() is true
  end
end

fun foo-is-false():
  check "foo is false":
    foo() is false
  end
end

[list: 
  # test to run; run?
  {foo-is-true;  true},
  {foo-is-false; false}
].each(lam(args): when args.{1}: args.{0}() end end)
```

The previous approach didn't scale because the checks are run at the end so they'd all use the latest value for skip. This list-based approach calls the functions containing each check depending on the boolean flag. That makes it straight-forward to update pending status. This also puts less boilerplate in the actual check so it's more readable.

**Comment by ErikSchierboom** [comment]
It might be worth adding a comment to the initially skipped tests to let students know what they need to know (besides also updating the test docs)

**Comment by BNAndras** [comment]
Great, I'll make a note to do that after we update the test runner.

**Comment by BNAndras** [comment]
The test runner is updated. Now, I need to update existing test files here to support pending tests and then update docs/TESTING.md with directions.

As a note, the final pattern can be seen at [https://github.com/exercism/pyret-test-runner/blob/main/tests/success-multiple/success-multiple-test.arr](https://github.com/exercism/pyret-test-runner/blob/main/tests/success-multiple/success-multiple-test.arr)

**Comment by BNAndras** [comment]
Okay, these are the slugs that need to be updated to support pending tests so this PR can be closed.

- [ ] acronym
- [ ] anagram
- [ ] armstrong-numbers
- [ ] atbash-cipher
- [ ] binary-search
- [ ] bob
- [ ] collatz-conjecture
- [ ] darts
- [ ] difference-of-squares
- [ ] dnd-character
- [ ] etl
- [ ] grains
- [ ] hamming
- [ ] hello-world
- [ ] isogram
- [ ] leap
- [ ] list-ops
- [ ] luhn
- [ ] matrix
- [ ] nucleotide-count
- [ ] pangram
- [ ] perfect-numbers
- [ ] phone-number
- [ ] protein-translation
- [ ] queen-attack
- [ ] raindrops
- [ ] resistor-color
- [ ] resistor-color-duo
- [ ] resistor-color-trio
- [ ] reverse-string
- [ ] rna-transcription
- [ ] roman-numerals
- [ ] scrabble-score
- [ ] secret-handshake
- [ ] series
- [ ] space-age
- [ ] square-root
- [ ] strain
- [ ] triangle
- [ ] two-fer
- [ ] word-count
